"""drop is_archived column

Revision ID: 83032c496e84
Revises: 3b0192c40a89
Create Date: 2025-08-26 15:59:35.552158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83032c496e84"
down_revision: Union[str, Sequence[str], None] = "3b0192c40a89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_archived")
    op.add_column(
        "tasks",
        sa.Column("active", sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "active")
